### PR TITLE
Rudimentary `servant-client` support and parsing of SSE events

### PR DESCRIPTION
**Pull request by adinapoli**
Hey @bflyblue ! Thanks for this great library, it was very useful to get started with adding support for SSE events for a project at work.

This patch is an initial stepping stone towards #4 (cc @kokobd as he was the original author of the issue). This PR does a bunch of things, most of which are shipped as a self-contained commit and should be easy to cherry-pick:

* Adds support for building with cabal out of the box by adding a `cabal.project` file;
* It supports (at least) GHC 9.2.8 with minimal modification to the dependencies bounds;
* It adds a working example that demonstrates how to use `servant-client` with this library to process SSE events sent by a server. When run, it will print something like this:

```
ServerEvent<info,1,Keep listening to server updates>
ServerEvent<notification,2,Update request received>
ServerEvent<info,3,Keep listening to server updates>
ServerEvent<info,4,Keep listening to server updates>
ServerEvent<message,5,Message at time 2023-11-01T07:29:33+00:00>
```

For this purpose I have added a rudimentary parser for SSE events that is used in the `MimeUnrenderer` instance that I have added, which makes this useable with `servant-client`. I haven't tested this extensively and it's surely perfectible, but it should be a decently-solid foundation we can iterate upon.

I'm happy to add more tests to test the parsing, if needed.

Let me know what you think!

### CODE REVIEW

**Comment by bflyblue** [comment]
Thank you!

I'm away on holiday but will be back home next week and will review your
changes :)

**Comment by adinapoli** [comment]
Excellent! No rush, and enjoy your holiday 😉

**Comment by bflyblue** [comment]
I've made breaking changes to the API to use servant's preferred streaming interface.

https://hackage.haskell.org/package/servant-0.20.2/docs/Servant-API-Stream.html

Would you mind taking a look before I send it to hackage for wider use?

**Comment by adinapoli** [comment]
> I've made breaking changes to the API to use servant's preferred streaming interface.
> 
> https://hackage.haskell.org/package/servant-0.20.2/docs/Servant-API-Stream.html
> 
> Would you mind taking a look before I send it to hackage for wider use?

Thanks, @bflyblue ! I don't have the full context in my head, as these days I'm not even leveraging the streaming interface at work anymore, but I agree that using whatever servant is mandating as de-facto these days makes sense.

Out of curiosity, did you retain/cherry-pick anything out of my PR? I have lost track exactly about what I did improve upon over the original design 😉

**Comment by bflyblue** [comment]
I plan to go back and cherry-pick some of your changes before submitting to Hackage, especially `serverEventParser` and the tests!

**Comment by adinapoli** [comment]
> I plan to go back and cherry-pick some of your changes before submitting to Hackage, especially `serverEventParser` and the tests!

Ah, great 😉 In which case, hopefully the tests will give you some confidence that the reworked approach is sound before it hits Hackage? Thanks for all the upgrades!

**Pull request closed without merging**
